name: Lighthouse
on:
  pull_request:
    branches:
      - main

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Lighthouse Check
        uses: foo-software/lighthouse-check-action@v8.0.0
        with:
          urls: "https://www.foo.software,https://www.google.com"
